<?php

namespace Anonsiero\AdvertBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function getCategories()
    {
        $query = $this->createQueryBuilder('a')
                    ->select('a.id, a.name')
                    ->join('a.parent', 'b')
                    ->addSelect('b.id as parent_id')
                    ->getQuery();
        return $query->getResult();
    }
}