<?php

namespace Anonsiero\AdvertBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FieldValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FieldValueRepository extends EntityRepository
{
}